# Generated by Django 2.2.3 on 2019-07-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_menu_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('no_topping', models.FloatField(max_length=64)),
                ('one_topping', models.FloatField(max_length=64)),
                ('two_topping', models.FloatField(max_length=64)),
                ('three_topping', models.FloatField(max_length=64)),
                ('special_topping', models.FloatField(max_length=64)),
            ],
        ),
    ]
