# Generated by Django 2.2.3 on 2019-09-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_toppings'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('user_id', models.IntegerField()),
                ('street_address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('phone_number', models.CharField(max_length=64)),
                ('notes', models.TextField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=64)),
            ],
            options={
                'verbose_name_plural': 'Orders Info',
            },
        ),
        migrations.CreateModel(
            name='OrdersItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
                ('size', models.CharField(max_length=64)),
                ('topping', models.CharField(max_length=64)),
                ('price', models.DecimalField(decimal_places=2, max_digits=64)),
            ],
            options={
                'verbose_name_plural': 'Orders Items',
            },
        ),
        migrations.CreateModel(
            name='OrdersToppings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('item_id', models.IntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Orders Toppings',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name_plural': 'Prices'},
        ),
        migrations.AlterModelOptions(
            name='toppings',
            options={'verbose_name_plural': 'Toppings'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
    ]
